### ISSUE TITLE
Add Workflow Behat integration

### ISSUE THREAD

**Issue by TravisCarden** [acquia/drupal-spec-tool#13]
Behat integration has been added for Workflow specifications. A "Workflows" tab was added to support specification of multiple, discrete workflows, and the "Workflow states" and "Workflow transitions" tabs were updated. See the "Behat" tab for the new feature, and add the new context to your [Behat configuration](http://behat.org/en/latest/user_guide/configuration.html) to make use of it, e.g.:

```yaml
# behat.yml
default:
  suites:
    default:
      contexts:
        - Acquia\DrupalSpecTool\Context\WorkflowContext
```

Note: Workflow diagram generation does not yet support multiple workflows https://github.com/acquia/drupal-spec-tool/issues/12
