### ISSUE TITLE
Add Views Behat integration

### ISSUE THREAD

**Issue by TravisCarden** [acquia/drupal-spec-tool#17]
Behat integration has been added for Views specification. See the "Behat" tab for the new feature, and add the new context to your [Behat configuration](http://behat.org/en/latest/user_guide/configuration.html) to make use of it, e.g.:

```yaml
# behat.yml
default:
  suites:
    default:
      contexts:
        - Acquia\DrupalSpecTool\Context\ViewsContext
```
