### ISSUE TITLE
Add support for Image styles

### ISSUE THREAD

**Issue by TravisCarden** [acquia/drupal-spec-tool#18]
Tabs and Behat integration have been added for Image styles specification. See the "Image styles", "Image effects", and "Behat" tabs for the new feature. Add the new context to your [Behat configuration](http://behat.org/en/latest/user_guide/configuration.html) to make use of it, e.g.:

```yaml
# behat.yml
default:
  suites:
    default:
      contexts:
        - Acquia\DrupalSpecTool\Context\MediaContext
```
